FROM openjdk:8-alpine AS openjava8

#Node version should match target cloud function deploy env
FROM node:10.18.1-alpine

COPY --from=openjava8 /usr/lib/jvm/java-1.8-openjdk /usr/lib/jvm/java-1.8-openjdk
ENV PATH="/usr/lib/jvm/java-1.8-openjdk/bin:${PATH}"

ARG CLOUD_SDK_VERSION=324.0.0
ENV CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION

RUN apk add --no-cache python3 curl bash openssh-client git grep zip coreutils

# Install gcloud
ENV PATH /google-cloud-sdk/bin:$PATH
RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
  tar xzf google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
  rm google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
  ln -s /lib /lib64 && \
  gcloud config set core/disable_usage_reporting true && \
  gcloud config set component_manager/disable_update_check true && \
  gcloud config set metrics/environment github_docker_image && \
  gcloud --version

# Install git-crypt
RUN curl --silent --output /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-git-crypt/master/sgerrand.rsa.pub && \
  curl -LO https://github.com/sgerrand/alpine-pkg-git-crypt/releases/download/0.6.0-r1/git-crypt-0.6.0-r1.apk && \
  apk add --no-cache git-crypt-0.6.0-r1.apk && \
  rm git-crypt-0.6.0-r1.apk

RUN npm i -g migrate@1.6.2 firebase-tools@8.4.1 firebase-admin@8.10.0 eslint eslint-config-airbnb-base eslint-plugin-import depcheck