FROM alpine:3.19.1

ARG CLOUD_SDK_VERSION=473.0.0
ENV CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION

ARG KUBECTL_VERSION=v1.21.14
ENV KUBECTL_VERSION=$KUBECTL_VERSION

# Dependencies
RUN apk add --no-cache \
    bash \
    binutils \
    ca-certificates \
    coreutils \
    curl \
    docker \
    docker-compose \
    findutils \
    g++ \
    gcc \
    git \
    git-crypt \
    gnupg \
    grep \
    jq \
    libc6-compat \
    libc-dev \
    libffi-dev \
    libgcc  \
    linux-headers \
    make \
    ncurses \
    npm \
    openssh-client \
    openssl-dev \
    py3-pip \
    python3-dev \
    python3 \
    py3-crcmod \
    rsync \
    util-linux \
    zip

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
ENV NVM_DIR /root/.nvm
ENV PATH $NVM_DIR:$PATH
RUN chmod +x $NVM_DIR/nvm.sh
RUN $NVM_DIR/nvm.sh --version
RUN $NVM_DIR/nvm.sh install 18
RUN $NVM_DIR/nvm.sh install 20
RUN $NVM_DIR/nvm.sh install 22
RUN $NVM_DIR/nvm.sh install 24

# install toolchain for rust as required by cryptography
RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- --default-toolchain stable -y
ENV PATH=/root/.cargo/bin:$PATH

# Install gcloud
ENV PATH /google-cloud-sdk/bin:$PATH
RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    tar xzf google-cloud-cli-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    rm google-cloud-cli-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
    ln -s /lib /lib64 && \
    gcloud config set core/disable_usage_reporting true && \
    gcloud config set component_manager/disable_update_check true && \
    gcloud config set metrics/environment github_docker_image && \
    gcloud components install gke-gcloud-auth-plugin && \
    gcloud --version

# Adds kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl \
    && chmod u+x kubectl && mv kubectl /usr/bin/kubectl
