FROM node:16-alpine

ARG CLOUD_SDK_VERSION=410.0.0
ENV CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION

RUN apk add --no-cache \
  curl \
  git \
  npm \
  yarn \
  coreutils \
  grep \ 
  zip \
  bash

# Install gcloud
ENV PATH /google-cloud-sdk/bin:$PATH
RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
  tar xzf google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
  rm google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz && \
  ln -s /lib /lib64 && \
  gcloud config set core/disable_usage_reporting true && \
  gcloud config set component_manager/disable_update_check true && \
  gcloud config set metrics/environment github_docker_image && \
  gcloud --version


RUN yarn global add turbo ts-node webpack webpack-cli
