FROM python:3.8.16-slim-buster

RUN apt-get update && apt-get install -y \
  curl \
  git \
  git-crypt \
  wget \
  zip \
  && rm -rf /var/lib/apt/lists/*

RUN pip install \
  dbt-bigquery~=1.2.0 \
  sqlfluff-templater-dbt