# Use an Ubuntu base image
FROM ubuntu:24.04

# Update package lists and install necessary dependencies
RUN apt-get update && apt-get install -y curl

# Download and install Postman CLI for x64 architecture
RUN curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh