version: 2.1
orbs:
  docker: circleci/docker@1.4.0

executors:
  base:
    docker:
      - image: cimg/base:2022.09

jobs:
  build_docker_images:
    executor: base
    steps:
      - checkout
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASS
      - run:
          name: build docker images
          command: |
            docker build -t playsportsgroup/buildtools -f Dockerfile


workflows:
  build:
    jobs:
      - build_docker_images:
          context: ['docker-hub-credentials']
          filters:
            branches:
              only:
                - ci

